development:
  authorized_keys_path: /tmp/tmuxme_development_authorized_keys

test: &test
  authorized_keys_path: /tmp/tmuxme_test_authorized_keys

production:
  authorized_keys_path: /home/tunnel/.ssh/authorized_keys

cucumber:
  <<: *test
